### ISSUE TITLE
Can't compile.

### ISSUE THREAD

**Issue by Achaean** [fastrgv/CoTerminalApps#1]
**Hi!** :-)

Issuing  "./lbuildall.sh" returns:

 ```
>./lbuildall.sh
./lbuildall.sh: line 1: lcmp.sh: command not found
./lbuildall.sh: line 2: lcmp.sh: command not found
./lbuildall.sh: line 3: lcmp.sh: command not found
./lbuildall.sh: line 4: lcmp.sh: command not found
./lbuildall.sh: line 5: lcmp.sh: command not found
./lbuildall.sh: line 6: lcmp.sh: command not found
./lbuildall.sh: line 7: lcmp.sh: command not found
./lbuildall.sh: line 8: lcmp.sh: command not found
./lbuildall.sh: line 9: lcmp.sh: command not found
./lbuildall.sh: line 10: lcmp.sh: command not found
./lbuildall.sh: line 12: lcmp.sh: command not found
./lbuildall.sh: line 13: lcmp.sh: command not found
./lbuildall.sh: line 14: lcmp.sh: command not found
./lbuildall.sh: line 15: lcmp.sh: command not found
>
```
I'm on Debian Jessie (oldstable) x64 KDE.
Gnatmake v.4.9.2.

**Comment by fastrgv** [comment]
Find "lcmp.sh", it should be in same directory;
make sure it is executable;
edit lbuildall.sh to use "./lcmp.sh" rather than "lcmp.sh" (sorry...my
fault)

**Comment by Achaean** [comment]
Indeed!
Putting a "./" at the beginning of each line, solved the problem.
Thanks! :-)
